server:
  name: "project-user"
  addr: "127.0.0.1:8080"
zap:
  debugFileName: "E:\\Environment\\GoWorks\\src\\ms_project\\logs\\debug\\project-debug.log"
  infoFileName: "E:\\Environment\\GoWorks\\src\\ms_project\\logs\\info\\project-info.log"
  warnFileName: "E:\\Environment\\GoWorks\\src\\ms_project\\logs\\error\\project-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
grpc:
  addr: "127.0.0.1:8881"
  name: "user"
  version: "1.0.0"
  weight: 2
etcd:
  addrs:
    - "127.0.0.1:2379"
